language: python
env:
  global:
    secure: "qn1eGzbR2K5TRaWgkJLfaCtuaYSsgdQTulHk74d+GQZr3YzAVB/zYW9QSrzWAuk7eS8yfRou47WR6jUiSucdQIc61geCWavsG/sC6XEAp8kQoAt5WnHoXfcEkRwrS+f1C3V9+no0LUlvWLa9xbeGIbsTT9Vx+cSwRbOtUYdmfDE="
branches:
  only:
    - src
install:
  - pip install pelican markdown
script:
  - PCO='.PCO#42' && pelican content -o ${PCO} -s pelicanconf.py && cp .travis.yml ${PCO} && git remote set-branches --add origin master && git fetch origin && git checkout master && rm -rf * && mv ${PCO}/{.[!.],}* . && rm -rf ${PCO} && git add . && git -c user.name='Travis CI' -c user.email='<>' commit -m "up" && ! git status --porcelain | grep -q . && if [[ "`ls -A -1 -I 'index?*.html' -I '.git' | cksum`" != "1676053246 40" ]]; then echo 'Trap ls,cksum FAIL - check pelican version ?'; exit 1; fi
after_success:
  - bash -c 'if [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then git push "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" master > /dev/null 2>&1 || exit 42; else echo "skip git push for PULL REQUEST"; fi'