dist: trusty
language: python
python:
  - "2.7"
branches:
  only:
    - src
before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en language-pack-ru && openssl aes-256-cbc -K $encrypted_de1cef0a973d_key -iv $encrypted_de1cef0a973d_iv -in github_deploy_key.enc -out github_deploy_key -d && chmod 600 github_deploy_key && eval `ssh-agent -s` && ssh-add github_deploy_key
install:
  - if [[ ${TRAVIS_PYTHON_VERSION} == '2.7'* ]]; then pip install -r requirements.txt; else exit 1; fi
before_script:
  - AD_PATCH="`pwd`/patches/adsense.patch" && cd `python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`/pelican/themes/notmyidea && patch -p1 < "$AD_PATCH" && cd -
script:
  - PCO='.PCO#42' && pelican content --fatal warnings -o ${PCO} -s publishconf.py && cp .travis.yml google6294828ff42db199.html ads.txt CNAME ${PCO} && git remote set-branches --add origin master && git fetch origin && git checkout master && rm -rf * && mv ${PCO}/{.[!.],}* . && rm -rf ${PCO} && git add -A && git -c user.name='Travis CI' -c user.email='<>' commit -m "up" && ! git status --porcelain | grep -q . && if [[ "`ls -A -1 -I 'index?*.html' -I '.git' | cksum`" != "3918989297 88" ]]; then echo 'Trap ls,cksum FAIL - check pelican version ?'; exit 1; fi
after_success:
  - bash -c 'if [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then git push "git@github.com:mazko/mazko.github.io.git" master > /dev/null 2>&1 || exit 42; else echo "skip git push for PULL REQUEST"; fi'
